swagger: "2.0"
info:
  title: OSE Killer
  description: API pour une plateforme de gestion de stage
  version: 1.0.0
host: localhost:8080
schemes:
  - http
paths:
  /student:
    put:
      summary: Retour d'un DTO étudiant avec si le courriel et mot de passe est valide.
      parameters:
        - in: body
          name: Paramètres
          description: Adresse courriel et mot de passe
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: DTO de l'étudiant
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              isConfirmed:
                type: boolean
              department:
                type: boolean
        404:
          description: Courriel et/ou mot de passe invalide
  /gestionnaire:
    put:
      summary: Retour d'un DTO gestionnaire avec si le courriel et mot de passe est valide.
      parameters:
        - in: body
          name: Paramètres
          description: Adresse courriel et mot de passe
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: DTO du gestionnaire
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              isConfirmed:
                type: boolean
              department:
                type: boolean
        404:
          description: Courriel et/ou mot de passe invalide
  /company:
    put:
      summary: Retour d'un DTO entreprise avec si le courriel et mot de passe est valide.
      parameters:
        - in: body
          name: Paramètres
          description: Adresse courriel et mot de passe
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: DTO de l'entreprise
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              isConfirmed:
                type: boolean
              department:
                type: boolean
        404:
          description: Courriel et/ou mot de passe invalide
  /8createStudentcreateStudent:
    post:
      summary: Crée un étudiant et envoie le courriel de confirmation
      parameters:
        - in: body
          name: Paramètres
          description: Objet contenant les informations de l'étudiant
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
              department:
                type: string
      produces:
        - application/json
      responses:
        201:
          description: Ne retourne pas d'objet
        409:
          description: Message d'erreur
          schema:
            type: object
            properties:
              error:
                type: string
  /createCompany:
    post:
      summary: Crée une compagnie et envoie le courriel de confirmation
      parameters:
        - in: body
          name: Paramètres
          description: Objet contenant les informations de la compagnie
          schema:
            type: object
            properties:
              name:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
              department:
                type: string
      produces:
        - application/json
      responses:
        201:
          description: Ne retourne pas d'objet
        409:
          description: Message d'erreur
          schema:
            type: object
            properties:
              error:
                type: string
  /createGestionaire:
    post:
      summary: Crée un gestionnaire et envoie le courriel de confirmation
      parameters:
        - in: body
          name: Paramètres
          description: Objet contenant les informations du gestionnaire
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
      produces:
        - application/json
      responses:
        201:
          description: Ne retourne pas d'objet
        409:
          description: Message d'erreur
          schema:
            type: object
            properties:
              error:
                type: string
  /confirmEmail/student/{id}:
    put:
      summary: Confirme le courriel d'un étudiant
      parameters:
        - in: path
          name: id
          description: id de l'étudiant
          type: string
          required: true
      produces:
        - application/json
      responses:
        201:
          description: Ne retourne pas d'objet
        404:
          description: Message d'erreur si etudiant non trouvé
          schema:
            type: object
            properties:
              error:
                type: string
        422:
          description: Message d'erreur si email exawpiré
          schema:
            type: object
            properties:
              error:
                type: string
  /confirmEmail/company/{id}:
    put:
      summary: Confirme le courriel d'une compagnie
      parameters:
        - in: path
          name: id
          description: id de la compagnie
          type: string
          required: true
      produces:
        - application/json
      responses:
        201:
          description: Ne retourne pas d'objet
        404:
          description: Message d'erreur si compagnie non trouvé
          schema:
            type: object
            properties:
              error:
                type: string
        422:
          description: Message d'erreur si email expiré
          schema:
            type: object
            properties:
              error:
                type: string
  /confirmEmail/gestionnaire/{id}:
    put:
      summary: Confirme le courriel d'un gestionnaire
      parameters:
        - in: path
          name: id
          description: id du gestionnaire
          type: string
          required: true
      produces:
        - application/json
      responses:
        201:
          description: Ne retourne pas d'objet
        404:
          description: Message d'erreur si gestionnaire non trouvé
          schema:
            type: object
            properties:
              error:
                type: string
        422:
          description: Message d'erreur si email expiré
          schema:
            type: object
            properties:
              error:
                type: string
  /createOffre:
    post:
      summary: Retour d'un DTO offre avec si le pdf est valide.
      parameters:
        - in: body
          name: Paramètres
          description: Nom de compagie department position heur par semaine adresse et pdf
          schema:
            type: object
            properties:
              nomDeCompagie:
                type: string
              department:
                type: string
              position:
                type: string
              heurParSemaine:
                type: integer
              adresse:
                type: string
              pdf:
                type: array
      produces:
        - application/json
      responses:
        200:
          description: Ne retourne rien
        404:
          description: Les champs ne peuvent pas être vide
          schema:
            type: object
            properties:
              error:
                type: string
  /validateCV/{id}:
    put:
      summary: Validé un cv par son id (Gestionnaire seulement)
      parameters:
        - in: path
          name: id
          description: id du CV
          type: string
          required: true
        - in: body
          name: token
          description: Token valide du gestionnaire
          schema:
            type: object
            properties:
              token:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: CV validé
        403:
          description: Token invalide ou expiré
        404:
          description: Un cv avec ce id n'existe pas ou le token est invalide
  /refuseCV/{id}:
    put:
      summary: Refuse un cv par son id (Gestionnaire seulement)
      parameters:
        - in: path
          name: id
          description: id du CV
          type: string
          required: true
        - in: body
          name: token
          description: Token valide du gestionnaire
          schema:
            type: object
            properties:
              token:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: CV refusé
        403:
          description: Token invalide ou expiré
        404:
          description: Un cv avec ce id n'existe pas
  /unvalidatedCVS:
    put:
      summary: Recevoir la listes des CVs à valider
      parameters:
        - in: body
          name: token
          description: Token valide du gestionnaire
          schema:
            type: object
            properties:
              token:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: Liste des CVs non validé
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                userId:
                  type: number
                cv:
                  type: array
                  items:
                    type: number
        403:
          description: Token invalide ou expiré
  /unvalidatedStudents:
    get:
      summary: Recevoir la listes des étudiants à valider
      produces:
        - application/json
      responses:
        200:
          description: Liste des étudiants non validés
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                isConfirmed:
                  type: boolean
                department:
                  type: string
                inscriptionTimestamp:
                  type: number
                emailConfirmed:
                  type: boolean
                cv:
                  type: array
                  items:
                    type: number
  /unvalidatedCompanies:
    get:
      summary: Recevoir la listes des compagnies à valider
      produces:
        - application/json
      responses:
        200:
          description: Liste des compagnies non validés
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                isConfirmed:
                  type: boolean
                department:
                  type: string
                inscriptionTimestamp:
                  type: number
                emailConfirmed:
                  type: boolean
                companyName:
                  type: string